pipeline:

  docker:
    image: plugins/docker
    repo: pinked/camera-synology-lister
    tags:
      - latest
      - ${DRONE_BUILD_NUMBER}
    secrets: [ docker_username, docker_password ]

  deploy:
    image: docker
    secrets: [ SYNOLOGY_USER, SYNOLOGY_PASS, SYNOLOGY_HOST ]
    commands:
      - docker deploy --compose-file docker-compose.yml cameras
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock