version: "3"
services:
  cams:
    networks:
      - proxy
    read_only: true
    deploy:
      replicas: 2
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=cameras.p.cns.me
        - com.df.port=3000
        - com.df.servicePath=/
        - com.df.httpsOnly=true
        - com.df.xForwardedProto=true
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 60s
        max_failure_ratio: 0.3
    image: pinked/camera-synology-lister
    environment:
      - SYNOLOGY_USER=${SYNOLOGY_USER}
      - SYNOLOGY_PASS=${SYNOLOGY_PASS}
      - SYNOLOGY_HOST=${SYNOLOGY_HOST}

networks:
  proxy:
    external: true